image: trion/ng-cli:11.2.6
stages:
  - building
  - testing
  - docker
  - deploying

# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#     - node_modules/

build:
  stage: building
  script:
    - npm ci
    - ng build --prod
  artifacts:
    paths:
      - dist/
    expire_in: 1 days
    when: always

# unit_test:
#   stage: testing
#   dependencies:
#     - build
#   image: efgiese/efgiese-angular-chrome-headless
#   script:
#     - npm run test-headless

# lint:
#   stage: testing
#   dependencies:
#     - build
#   script:
#     - ng lint ipsenh-frontend

docker:
  stage: docker
  dependencies:
    - build
  image: docker:19.03.12
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:19.03.12-dind
  script:
    - docker build -t ipsenh-groep7-frontend .
    
deploy:
  stage: deploying
  dependencies:
    - docker
  script:
    - ls

