image: trion/ng-cli:11.2.6
stages:
  - preparation
  - sleeping
  - testing
  - building
  - deploying

npm:
  stage: preparation
  script:
    - npm -v
    - npm ci
  cache:
    key: npm_cache
    paths:
      - node_modules/

#https://gitlab.com/gitlab-org/gitlab/-/issues/21409
await_cache:
  stage: sleeping
  dependencies:
    - npm
  script:
    - sleep 90

unit_test:
  stage: testing
  dependencies:
    - await_cache
  image: efgiese/efgiese-angular-chrome-headless
  cache:
    key: npm_cache
  script:
    - npm run test-headless

lint:
  stage: testing
  dependencies:
    - await_cache
  cache:
    key: npm_cache
  script:
    - ng lint ipsenh-frontend

build:
  stage: building
  dependencies:
    - unit_test
    - lint
  cache:
    key: npm_cache
  script:
    - ng build --prod
  artifacts:
    paths:
      - dist/
    expire_in: 1 days
    when: always

deploy:
  stage: deploying
  dependencies:
    - build
  script:
    - echo "deploy hoi"

