image: node:latest
stages:
  - build
  - test
  - deploy

before_script:
  - npm install

#cache:
#  paths:
#    - ./node_modules

build:
  stage: build
  script:
    - echo "this is a build stage"


test:
  stage: test
  script:
    - echo "this is the test stage"

deploy:
  stage: deploy
  script:
    - echo "this is the deploy stage"
