image: efgiese/efgiese-angular-chrome-headless
stages:
  - install
  - test

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm ci
  only:
    - master
    - develop

test_unit:
  stage: test
  script:
    - npm run test-headless

test_lint:
  stage: test
  script:
    - ng lint ipsenh-frontend
