image: node:latest
stages:
  - build
  - test
  - deploy

#cache:
#  paths:
#    - ./node_modules

build:
  stage: build
  script:
    - npm install
    - npm link @angular/cli
    - ng build --prod
  only:
    - master
    - develop
  cache:
    paths:
      - node_modules


test:
  stage: test
  script:
    - echo "this is the test stage"

deploy:
  stage: deploy
  script:
    - echo "this is the deploy stage"
