image: trion/ng-cli:11.2.6
stages:
  - building
  - testing
  - publishing
  - deploying

cache: &global_cache
  key: ${CI_JOB_NAME}
  untracked: true
  paths:
    - node_modules/

build:app:
  stage: building
  script:
    - npm ci
    - ng build --prod
  artifacts:
    paths:
      - dist/
    expire_in: 7 days
    when: always

test:unit:
  stage: testing
  image: efgiese/efgiese-angular-chrome-headless
  script:
    - npm run test-headless
  cache:
    <<: *global_cache
    policy: pull

test:lint:
  stage: testing
  script:
    - ng lint ipsenh-frontend
  cache:
    <<: *global_cache
    policy: pull

publish:docker-staging:
  stage: publishing
  image: docker:19.03.12
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:19.03.0-dind
      command: ["--insecure-registry","gitlab.groep-7.xyz:5050"]
  script:
    - docker login -u $PROJECT_TOKEN_USERNAME -p $PROJECT_TOKEN_PASSWORD $CONTAINER_REGISTRY
    - docker build -t $STAGING_IMAGE_TAG:$CI_COMMIT_SHORT_SHA -t $STAGING_IMAGE_TAG:latest .
    - docker push $STAGING_IMAGE_TAG:$CI_COMMIT_SHORT_SHA
    - docker push $STAGING_IMAGE_TAG:latest
  cache: {}
  only:
    - development

publish:docker-production:
  stage: publishing
  image: docker:19.03.12
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:19.03.0-dind
      command: ["--insecure-registry","gitlab.groep-7.xyz:5050"]
  script:
    - docker login -u $PROJECT_TOKEN_USERNAME -p $PROJECT_TOKEN_PASSWORD $CONTAINER_REGISTRY
    - docker build -t $PRODUCTION_IMAGE_TAG:$CI_COMMIT_SHORT_SHA -t $PRODUCTION_IMAGE_TAG:latest .
    - docker push $PRODUCTION_IMAGE_TAG:$CI_COMMIT_SHORT_SHA
    - docker push $PRODUCTION_IMAGE_TAG:latest
  cache: {}
  only:
    - master

deploy:staging-app:
  stage: deploying
  image: alpine
  before_script:
    - apk add openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  script:
    - ssh -o StrictHostKeychecking=no $SERVER_USER@$SERVER_IP "bash $DEPLOY_SCRIPT
      -u $PROJECT_TOKEN_USERNAME
      -p $PROJECT_TOKEN_PASSWORD
      -r $CONTAINER_REGISTRY
      -i $STAGING_IMAGE_TAG:$CI_COMMIT_SHORT_SHA
      -e staging -s staging_angular"
  cache: {}
  only:
    - development
  environment:
    name: staging

deploy:production-app:
  stage: deploying
  image: alpine
  before_script:
    - apk add openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  script:
    - ssh -o StrictHostKeychecking=no $SERVER_USER@$SERVER_IP "bash $DEPLOY_SCRIPT
      -u $PROJECT_TOKEN_USERNAME
      -p $PROJECT_TOKEN_PASSWORD
      -r $CONTAINER_REGISTRY
      -i $PRODUCTION_IMAGE_TAG:$CI_COMMIT_SHORT_SHA
      -e production -s production_angular"
  cache: {}
  only:
    - master
  environment:
    name: production
