image: trion/ng-cli:11.2.6
stages:
  - preparation
  - sleeping
  - testing
  - building
  - deploying

before_script:
  - npm install

npm:
  stage: preparation
  script:
    - npm -v
    - npm ci
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

unit_test:
  stage: testing
  dependencies:
    - npm
  image: efgiese/efgiese-angular-chrome-headless
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm run test-headless

lint:
  stage: testing
  dependencies:
    - npm
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm ci
    - ng lint ipsenh-frontend

build:
  stage: building
  dependencies:
    - unit_test
    - lint
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - ng build --prod
  artifacts:
    paths:
      - dist/
    expire_in: 1 days
    when: always

docker:
  stage: building
  image: docker:19.03.12
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:19.03.12-dind
  script:
    - docker build -t ipsenh-groep7-frontend .


# deploy:
#   stage: deploying
#   dependencies:
#     - build
#   script:
#     - echo "deploy hoi"

