image: trion/ng-cli:11.2.6
stages:
  - install
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install -g --cache --silent
    - npm install -g @angular/cli
    - npm run test
#    - ./node_modules/.bin/ng test
  only:
    - master
    - develop

test:
  stage: test
  script:
#    - ng test
    - ng lint ipsenh-frontend

#build:
#  stage: build
#  script:
#    - echo "test"
##    - ng build --prod
#  only:
#    - master
#    - develop
#
#deploy:
#  stage: deploy
#  script:
#    - echo "this is the deploy stage"
