image: node:latest
stages:
  - install
  - test
  - build
  - deploy

#cache:
#  paths:
#    - ./node_modules

install:
  stage: install
  script:
    - npm install -g --cache --silent

test:
  stage: test
  script:
    - ng test
    - ng lint ipsenh-frontend

build:
  stage: build
  script:
    - echo "test"
#    - npm link @angular/cli
#    - ng build --prod
  only:
    - master
    - develop

deploy:
  stage: deploy
  script:
    - echo "this is the deploy stage"
