image: trion/ng-cli:11.2.6
stages:
  - test

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

test:
  stage: test
  before_script:
    - npm ci
    # - npm install --silent
  script:
    - npm run test-headless
    - ng lint ipsenh-frontend
