image: trion/ng-cli:11.2.6
stages:
  - test

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

test_unit:
  stage: test
  before_script:
    - npm ci
  script:
    - npm run test-headless

test_lint:
  stage: test
  before_script:
    - npm ci
  script:
    - ng lint ipsenh-frontend
