image: trion/ng-cli:11.2.6
stages:
  - installing
  - building
  - testing
  - deploying

cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

npm:
  stage: installing
  script:
    - npm ci

build:
  stage: building
  dependencies:
    - npm
  script:
    - ng build --prod
  artifacts:
    paths:
      - dist/
    expire_in: 1 days
    when: always

unit_test:
  stage: testing
  dependencies:
    - build
  image: efgiese/efgiese-angular-chrome-headless
  script:
    - npm run test-headless

lint:
  stage: testing
  dependencies:
    - build
  script:
    - ng lint ipsenh-frontend

deploy:
  stage: deploying
  dependencies:
    - unit_test
    - lint
  image: docker:19.03.12
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:19.03.0-dind
      command: ["--insecure-registry","gitlab.groep-7.xyz:5050"]
  script:
    - docker login -u gitlab+deploy-token-1 -p LBePBpNrf42vzB8kdTQn gitlab.groep-7.xyz:5050
    - docker build -t gitlab.groep-7.xyz:5050/ashnawiar/ipsenh-frontend .
    - docker push gitlab.groep-7.xyz:5050/ashnawiar/ipsenh-frontend

