version: "3.9"
services:
  webapp:
    build: .
    ports:
      - "80:80"
    container_name: angular
    volumes:
      - "./dist/ipsenh-frontend:/usr/share/nginx/html"
    networks:
      - ipsenh-backend_lumen

networks:
  ipsenh-backend_lumen:
    external: true
